query getOrderCustomData($orderId: String) {
  getOrder(orderId: $orderId) {
    status
    data {
      customData {
        customApps {
          fields {
            data
          }
          id
        }
      }
    }
  }
}
